algoritmo "Atividade7"

var
  a, b, c, d:real

inicio

  EscrevaL ("Sen(30) =",Sen(30))
  EscrevaL ("Cos(30) =",Cos(30))
    EscrevaL("")
  EscrevaL ("Sen(45) =",Sen(45))
  EscrevaL ("Cos(45) =",Cos(45))
    EscrevaL("")
  EscrevaL ("Sen(60) =",Sen(60))
  EscrevaL ("Cos(60) =",Cos(60))
    EscrevaL("")
  EscrevaL ("Sen(90) =",Sen(90))
  EscrevaL ("Cos(90) =",Cos(90))


fimalgoritmo
