algoritmo "testedaAula"

var
  a, b, c:inteiro

inicio

   a <- 2
   b <- 3
   c <- 5
   EscrevaL ("A =",a)
   EscrevaL ("B =",b)
   EscrevaL ("C =",c)
   EscrevaL ("A > B ?", a<b)
   EscrevaL ("A > C ?", a>c)
   EscrevaL ("A = B ?", a=b)
   EscrevaL ("A <= C ?", a<=c)
   EscrevaL ("A <> B ?", a<>b)
   EscrevaL ("A > 2 ?", a>2)
   EscrevaL ("A + B = C ?", a+b=c)
   EscrevaL ("A + C = B ?", a+c=b)
   EscrevaL ("C >= B ^ A?",  c>=b^a)

fimalgoritmo
