algoritmo "Atividade6"

var
  a, b, c, d:real

inicio

  EscrevaL ("Sen(30) =",Sen(GraupRad(30)))
  EscrevaL ("Cos(30) =",Cos(GraupRad(30)))
    EscrevaL("")
  EscrevaL ("Sen(45) =",Sen(GraupRad(45)))
  EscrevaL ("Cos(45) =",Cos(GraupRad(45)))
    EscrevaL("")
  EscrevaL ("Sen(60) =",Sen(GraupRad(60)))
  EscrevaL ("Cos(60) =",Cos(GraupRad(60)))
    EscrevaL("")
  EscrevaL ("Sen(90) =",Sen(GraupRad(90)))
  EscrevaL ("Cos(90) =",Cos(GraupRad(90)))


fimalgoritmo
