algoritmo "SomaESubtraçãoDeNumeros"

var

   nome:Caractere
   n1, n2:inteiro
   


inicio

   EscrevaL ("Digite seu nome: ",nome) //seu nome
   Leia (nome)
   EscrevaL("Vamos somar dois numeros inteiros?")
   EscrevaL ("Digite o primeiro numero: ", n1)//numero um
   Leia (n1)
   EscrevaL ("Digite o segundo numero: ", n2)//numero dois
   Leia(n2)
   EscrevaL ("Resultado da Soma: ", n1 + n2) //soma de ambos

   EscrevaL ("")


fimalgoritmo
