algoritmo "EX087"
var

a :Caractere

Procedimento gerador (a :Caractere)

inicio

 EscrevaL ("--------------------------------------------------")
 EscrevaL (                       a                            )
 EscrevaL ("--------------------------------------------------")

fimprocedimento

inicio
   EscrevaL ("Digite a mensagem do dia: ")
   Leia (a)
   LimpaTela
   Gerador (a)

fimalgoritmo
